name: Auto Doc Generation

on:
  push:
    branches:
      - main

jobs:
  # auto_doc_generation:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Generate Docs
  #       uses: gianfrancodemarco/zero-docs-action@main
  #       with:
  #         openai-api-key: ${{ secrets.OPENAI_API_KEY }}
  #         scan-dir: tests
  #         files: null
  #         reviewers: gianfrancodemarco
  fetch_files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          since_last_remote_commit: true 

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  auto_doc_generation_only_modified_files:
    runs-on: ubuntu-latest
    needs: fetch_files
    steps:

      - name: Print the output
        run: echo "The files are ${{ needs.fetch_files.outputs.all_changed_files }}" && echo "The files are ${{ needs.fetch_files.outputs.files }}"

      - name: Generate Docs
        uses: gianfrancodemarco/zero-docs-action@main
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          paths: ${{ needs.fetch_files.outputs.all_changed_files }}
          reviewers: gianfrancodemarco