name: Auto Doc Generation

on:
  push:
    branches:
      - main

jobs:
  # auto_doc_generation:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Generate Docs
  #       uses: gianfrancodemarco/zero-docs-action@main
  #       with:
  #         openai-api-key: ${{ secrets.OPENAI_API_KEY }}
  #         scan-dir: tests
  #         files: null
  #         reviewers: gianfrancodemarco
  fetch_files:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          since_last_remote_commit: true 

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
        
      - name: Fetch modified files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "::set-output name=files::${ALL_CHANGED_FILES}"

  auto_doc_generation_only_modified_files:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Docs
        uses: gianfrancodemarco/zero-docs-action@main
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          paths: ${{ steps.fetch_files.outputs.files }}
          reviewers: gianfrancodemarco